server:
  bind:
    host: 0.0.0.0
    port: 5000
  url: http://localhost:5000
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    # First language is the default language
    - en-US
  # cors: true
  pretty_print: true
  limit: 10
  # templates:
  # path: /path/to/Jinja2/templates
  # static: /path/to/static/folder # css/js/img
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
#    manager:
#        name: TinyDB
#        connection: /tmp/pygeoapi-process-manager.db
#        output_dir: /tmp/
# ogc_schemas_location: /opt/schemas.opengis.net

logging:
  level: ERROR
  #logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title:
      en: EOEPCA pygeoapi
    description:
      en: pygeoapi instance for the EOEPCA project
    keywords:
      en:
        - geospatial
        - data
        - api
        - eoepca
        - earth observation
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://eoepca.org
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: EOEPCA+
    url: https://eoepca.org/
  contact:
    name: Jankovic, Nikola
    position: Senior Geospatial Engineer
    address: Thurngasse 8/4
    city: Vienna
    stateorprovince: Vienna
    postalcode: 1090
    country: Austria
    # phone: +xx-xxx-xxx-xxxx
    # fax: +xx-xxx-xxx-xxxx
    email: nikola.jankovic@eox.at
    url: https://eox.at
    hours: Mo-Fr 08:00-17:00
    instructions: During hours of service. Off on weekends.
    role: pointOfContact

resources:
  sentinel-2-l2a:
    type: collection
    title: Sentinel 2 L2A
    description: Sentinel 2 L2A
    keywords:
      - sentinel2
    links:
      - type: text/html
        rel: canonical
        title: information
        href: https://eoapi.develop.eoepca.org/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: map
        name: eoapi_maps_plugin.EOAPIProvider
        data: https://eoapi.develop.eoepca.org/raster
        options:
          stac_collection: sentinel-2-l2a
          default_asset: TCI_10m
        format:
          name: png
          mimetype: image/png
